#my:
#  foo: foo version 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
#server:
#  port: 8762