eureka:
  instance:
    hostname: zuul
    prefer-ip-address: true
    ip-address: 47.111.232.105
#    ip-address: 192.168.1.37
  client:
    service-url:
#      defaultZone: http://test:123456@0.0.0.0:8761/eureka/
      defaultZone: http://test:123456@47.111.232.105:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-dujunjie-test:
      path: /dujunjie-test/**
      serviceId: dujunjie-test
    api-login-authority-system:
      path: /login-authority-system/**
      serviceId: login-authority-system
    api-organization:
      path: /organization/**
      serviceId: organization
    api-organization2:
      path: /organization2/**
      serviceId: organization2
    api-project-manager:
      path: /ssm/**
      serviceId: project-manager
    api-crm:
      path: /crm/**
      serviceId: crm-system
    api-BASIC:
      path: /basic/**
      serviceId: BASIC
    api-process:
      path: /process/**
      serviceId: process
#  prefix: /V1



