#my:
#  foo: foo version 1
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#        git:
#          uri: https://github.com/afterchj/spring-cloud-demo
#          search-paths: config
#      label: master
  profiles:
    active: native
  application:
       name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
