#my:
#  foo: foo version 1
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/afterchj/spring-could-demo
          search-paths: config
#        native:
#          search-locations: classpath:/shared
      label: master
  application:
       name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769

#server:
#  port: 8762